-------------------------------------------------------------------------------
--  ▖▖▄▖▄▖
--  ▌▌▄▌▛▌
--  ▚▘▙▖█▌
--
--  @file      v20.ads
--  @copyright See authors list below and v20.copyrights file
--  @licence   GPL v3
--  @encoding  UTF-8
-------------------------------------------------------------------------------
--  @summary
--  V20 library definitions
--
--  @description
--
--  @authors
--  Stéphane Rivière - sr - sriviere@soweb.io
--
--  @versions
--  20210317 0.1   sr        Initial release
--  20210322 0.1   sr - tio: Integration
--                      cfg: Integration
--  20210322 0.2   sr - v20: Refactoring - standardize renames, help for
--                           GNATdoc, reorder and add many functions, delete
--                           all Integer and Real related types, put generics
--                           and functions private
--  20210402 0.2   sr - cfg: Log, prg, tio & vst: basic coding done
--  20210409 0.2   sr - prg: Fix a bunch of small bugs, Put refactoring
--  20210411 0.3   sr - fls: Enhance Create
--                      sys: Refactoring 
--  20210414 0.4   sr - log: Adjust again Line_Max_Length
--  20210731 0.5   sr - v20: API consistency: All strings constants and 
--                           function only returns VString typed. All strings
--                           parameters accept both String and VString types.
--  20210804 0.6   sr - v20: Fix a RTE when a program is launched through a 
--                           symbolic link. Add Get_Build function. Extend 
--                           procedure Raise_Exception
--  20211012 0.7   sr - vst: 20211012 Fix typos, add numerous functions, mainly
--                           in Vst package
--  20211214 0.8   sr - tio: Add Cursor_Off/On & Duration_Stamp_Seconds 
--  20211220 0.9   sr - sql: SQLite integration
--  20220129 0.10  sr - sql: SQLite high level integration
--                      vst: Add Replace_Pattern, Field_Display and more
--                      v20: Add redirection and ASCII constants
--  20220221 0.11  sr - net: Network package integration
--                      sql: Many bugfixes and enhancement
--                      v20: Many enhancements and new routines in fls, prg, 
--                           tio and vst
--  20220717 0.12  sr - all: Many bugfixes and new enhancement in all packages.
--                      sql: Read and Search functions enhancements.  Overall
--                           improvement of the management of anomalies and
--                           exceptions at the opening of the database.   
-------------------------------------------------------------------------------

with Ada.Exceptions;
--with Interfaces; use Interfaces;
with Ada.Strings.Unbounded;

package v20 is

   -- Can't use v20-vst to avoid circular references
   package ASU renames Ada.Strings.Unbounded;
   
   type Unsigned_Integer8 is mod 256;
   --subtype Integer_64 is Interfaces.Integer_64;
   
   --  Redirection constants
   STD_OUT_REDIRECT  : constant String := " 1>/dev/null";
   ERR_OUT_REDIRECT  : constant String := " 2>/dev/null";
   STD_ERR_OUT_REDIRECT : constant String := " 2>/dev/null 1>/dev/null";
   
   -- Flag files
   ACCESS_OK : constant String := "access_ok_dont_delete_this_file";
   INSTALL_OK : constant String := "install_ok_dont_delete_this_file";
   
   --  String constants
   
   -- Force a true (without an apostrophe pair generated by 'Image attribute) 
   -- character to string conversion by adding a trailing empty string.
   HT   : constant String := Character'Val(9)  & ""; -- 09d 09h Tab
   LF   : constant String := Character'Val(10) & ""; -- 10d 0Ah Line Feed
   CR   : constant String := Character'Val(13) & ""; -- 13d 0Dh Carriage return
   ESC  : constant String := Character'Val(27) & ""; -- 27d 1Bh Escape
   DQ   : constant String := Character'Val(34) & ""; -- 34d 22h Double quote
   CRLF : constant String := CR & LF;
   
   ND : constant String := "~"; -- 126d 7Eh Name/value delimiter
   CD : constant String := "^"; --  94d 5Eh Column delimiter
   RD : constant String := "\"; --  92d 5Ch Row delimiter
   VD : constant String := ","; --  44d 2Ch Virgule (comma) delimiter
   DD : constant String := ","; --  46d 2Eh Dot delimiter
   SD : constant String := ":"; --  58d 3Ah Colon delimiter
   SP : constant String := " "; --  32d 20h Space

   -- ANSI colors (ISO 6429 standard)
   CONSOLE_COLOR_GREEN  : constant String := ESC & "[1;32m";
   CONSOLE_COLOR_RED    : constant String := ESC & "[1;31m";
   CONSOLE_COLOR_YELLOW : constant String := ESC & "[1;33m";
   CONSOLE_COLOR_RESET  : constant String := ESC & "[0m";

   function Get_Version return ASU.Unbounded_String;
   --  Returns the Library name and formatted version like:
   --  “v20 v.minor.major”.
   
   function Get_Build return ASU.Unbounded_String;
   --  Returns the formatted build date stamp like:
   --  “build YYYY-mm-dd hh:mm:ss”.

   function Get_Log_Dir return ASU.Unbounded_String;
   --  Returns the log directory

   function Get_Tmp_Dir return ASU.Unbounded_String;
   --  Returns the temporary files directory

   procedure Raise_Exception;
   --  Raise an exception for reporting test and <program_Name.err> file
   --  creation. In addition to the usual trace, a v20 exception give some
   --  extra information like : exception time, program uptime, program &
   --  library names & versions, start & home directories and Ada and all
   --  languages memory allocation, current & maximum (peak) values.

   procedure Exception_Handling
   (Exception_Hook : Ada.Exceptions.Exception_Occurrence);
   --  Process exceptions.

-------------------------------------------------------------------------------
private

   Name : constant String := "v20";
   --  Library's name

   Version_Major : constant Natural := 0;
   --  Library major version number

   Version_Minor : constant Natural := 11;
   --  Library minor version number

   --  135 cols width is the max full screen standard console on a rather old,
   --  but so good, Dell UltraSharp 1907Fp 1280x1024 4:3 monitor
   --  92 cols width is the max length useable in the "Listing 7" paragraph 
   --  style of AIDE Manual with B612 font.
   --  79 is the standard width.

   Line_Max_Length : constant Natural := 255;
   Title_Max_Length : constant Natural := 85;
   --  Maximum line length for exceptions (.err) and log reports (.log)

   Log_Dir : constant String := "/var/log/";
   --  Log directory
   
   Tmp_Dir : constant String := "/tmp/";
   --  Temporary directory

   Errorlevel : Natural := 0;

------------------------------------------------------------------------------
end v20;
------------------------------------------------------------------------------
